stages:
  - test
  - build

test:
  stage: test
  image: python:3.9-slim
  services:
    - name: openrouteservice/openrouteservice:v6.4.3
      alias: ors
    - name: registry.gitlab.com/dangoclub/postgis
      alias: pg
  script:
    - pip install -r requirements.txt
    - flask db upgrade
    - pip install pytest==6.2.4
    - pytest -v

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --cache=true
      --context "$CI_PROJECT_DIR"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" 
      --destination "${CI_REGISTRY_IMAGE}:${TAG}"
  rules:
    - if: "$CI_COMMIT_TAG"
      variables:
        TAG: "$CI_COMMIT_TAG"
    # - if: '($CI_COMMIT_BRANCH) && ($CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH)'
    #   variables:
    #     TAG: "$CI_COMMIT_SHORT_SHA"
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      variables:
        TAG: "latest"
