stages:
  - build
  - test

default:
  image: python:3.9-slim

build:
  stage: build
  # image: docker:20.10.6
  services:
    - docker:20.10.6-dind
  script:
    - docker build -t registry.gitlab.com/dangoclub/geo .
    - docker run -v 8000:8000 registry.gitlab.com/dangoclub/geo
    # - docker login -u driveandgoproject@gmail.com -p _rrzFap8gan13YR1psnz registry.gitlab.com 

test:
  stage: test
  script:
      # - python manage.py runserver 0.0.0.0:8000 
      - python tests/test.py