   

# test:
#   stage: test
#   script:
#     - pip install -r requirements.txt
#     - python manage.py runserver 0.0.0.0:8000 
#     - python tests/test.py

build:
  stage: build
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - > 
      /kaniko/executor
      --cache=true
      --context "$CI_PROJECT_DIR"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" 
      --destination "${CI_REGISTRY_IMAGE}:${TAG}"
  rules:
    # - if: '"$CI_MERGE_REQUEST_ID"'
    #   when: never
    - if: '"$CI_COMMIT_TAG"'
      variables:
        TAG: "$CI_COMMIT_TAG"
    - if: '("$CI_COMMIT_BRANCH") && ("$CI_COMMIT_BRANCH" != "$CI_DEFAULT_BRANCH")'
      variables:
        TAG: "$CI_COMMIT_SHA"
    - if: '"$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH"'
      variables:
        TAG: "latest"
