stages:
  - test
  - build

default:
  image: python:3.9-slim

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py runserver 0.0.0.0:8000 
    - python tests/test.py

build:
  stage: build
  image: docker:20.10.6
  services:
    - docker:20.10.6-dind
  dependencies:
    - test
  script:
    - docker build -t registry.gitlab.com/dangoclub/geo .
    - docker run -p 8000:8000 registry.gitlab.com/dangoclub/geo
    - docker login -u CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push 
