version: "3.9"
services:
  api:
    image: registry.gitlab.com/dangoclub/geo:dcbace4c
    restart: always
    environment:
      FLASK_ENV: "$FLASK_ENV"
    ports:
      - "5000:5000"
    networks:
      - geo
    depends_on:
      ors:
        condition: service_healthy
      pg:
        condition: service_started
  ors:
    image: gnedaev/dango-ors
    restart: always
    networks:
      - geo
  pg:
    image: gnedaev/pg-mmo-roads
    restart: always
    networks:
      - geo

networks:
  geo: {}
    