version: "3.9"
services:
  api:
    image: registry.gitlab.com/dangoclub/geo
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      ors:
        condition: service_healthy
      pg:
        condition: service_started
  ors:
    image: registry.gitlab.com/dangoclub/ors
    restart: always
  pg:
    image: registry.gitlab.com/dangoclub/postgis
    user: postgres
    restart: always
    