version: "3.9"
services:
  api:
    image: registry.gitlab.com/dangoclub/geo
    restart: always
    environment:
      FLASK_ENV: "$FLASK_ENV"
    ports:
      - "5000:5000"
    depends_on:
      ors:
        condition: service_healthy
      pg:
        condition: service_started
  ors:
    image: registry.gitlab.com/dangoclub/ors
    restart: always
  pg:
    image: registry.gitlab.com/dangoclub/postgis
    restart: always
    