version: "3.9"
services:
  api:
    image: registry.gitlab.com/dangoclub/geo
    command: sh -c "flask db upgrade && gunicorn -b=0.0.0.0:5000 -w 4 app:app"
    restart: always
    env_file:
      - .env
    expose:
      - 5000
    depends_on:
      ors:
        condition: service_healthy
      pg:
        condition: service_started
  nginx:
    image: registry.gitlab.com/dangoclub/nginx
    ports: 
      - 80:80
    depends_on:
      - api
  ors:
    image: registry.gitlab.com/dangoclub/ors
    restart: always
  pg:
    image: registry.gitlab.com/dangoclub/postgis
    restart: always
  autoheal:
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    