version: '3.9'
services:
  api:
    image: registry.gitlab.com/dangoclub/geo
    command: sh -c "flask db upgrade && gunicorn -b=0.0.0.0:5000 -w 4 app:app"
    restart: unless-stopped	
    env_file:
      - .env
    ports:
      - 10.0.0.3:${API_PORT}:5000
    depends_on:
      ors:
        condition: service_healthy
      pg:
        condition: service_started
  ors:
    image: registry.gitlab.com/dangoclub/ors
    restart: unless-stopped	
  pg:
    image: registry.gitlab.com/dangoclub/postgis
    restart: unless-stopped	
  autoheal:
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped	
    