---
openapi: "3.0.3"
info:
  version: "1.0.0"
  title: Geo
  description: Dango Geo API
  contact:
    name: Grigory Nedaev
    email: nedaevg@gmail.com
servers:
  - url: "http://89.108.70.197:5000"
    description: Development server
paths:
  "/":
    get:
      operationId: app.routes.healthcheck
      summary: Health Check
      description: Returns 200 and status OK as JSON if the API is working
      responses:
        200:
          description: The API is up and running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: OK if working
  "/directions":
    post:
      operationId: app.routes.directions
      summary: Build a route via the OpenRouteService
      description: |
        Build a car or walking route using the specified locations or other routes, and save it to the database
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                positions:
                  type: array
                  items:
                    $ref: "#/components/schemas/Position"
                profile:
                  description: "Transportation mode: either car or walking"
                  type: string
                  enum:
                    - "driving-car"
                    - "foot-walking"
                user_id:
                  $ref: "#/components/schemas/UUID"
                from_route_id:
                  $ref: "#/components/schemas/UUID"
                to_route_id:
                  $ref: "#/components/schemas/UUID"
                make_route:
                  description: In some cases no route is actually needed, the goal is just to save to endpoints
                  type: boolean
                  default: true
                alternatives:
                  description: Whether to suggest alternative routes
                  type: boolean
                  default: true
                handles:
                  description: Whether to return a mid-point for each route so the user could drag it to re-route
                  type: boolean
                  default: true
              required:
                - profile
                - user_id
              additionalProperties: false
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  routes:
                    type: array
                    items:
                      $ref: "#/components/schemas/Feature"
                      geometryType: LineString
                  prepared_routes:
                    type: array
                    items:
                      $ref: "#/components/schemas/Feature"
                      "type": LineString
                  handles:
                    type: array
                    items:
                      $ref: "#/components/schemas/Feature"
                      "type": Point
  "/routes/{route_id}":
    parameters:
      - $ref: "#/components/parameters/routeID"
    get:
      summary: Get Route
      description: Retrieve an existing route from the database
      operationId: app.routes.get_route
      parameters:
        - name: full
          in: query
          description: Whether to return the route's geometry, or just the endpoints
          schema:
            type: boolean
            default: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  full:
                    type: boolean
                    description: Whether the full route's geometry is returned or just the endpoints
                  route:
                    $ref: "#/components/schemas/Feature"
                    geometryType: LineString
        404:
          $ref: "#/components/responses/RouteNotFound"
    put:
      summary: Select Route
      description: Delete all user's route other than specified by `route_id` and assign it `trip_id`
      operationId: app.routes.delete_discarded_routes
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/UUID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trip_id:
                  $ref: "#/components/schemas/UUID"
              required:
                - trip_id
              additionalProperties: false
      responses:
        204:
          description: |
            The selected route was successfully updated. The user's other routes were deleted.
        400:
          description: Such `trip_id` already exist in the database
        404:
          description: No such route and user combination
  "/routes/{route_id}/immitate":
    post:
      summary: Immitate a driver's route
      description: Distort an existing route by simulating GPS inaccuracy
      operationId: app.routes.immitate
      parameters:
        - $ref: "#/components/parameters/routeID"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                positions:
                  type: array
                  description: Arbitrary positions that the immitated route should include
                  items:
                    $ref: "#/components/schemas/Position"
              required:
                - positions
              additionalProperties: false
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feature"
                geometryType: LineString
        404:
          $ref: "#/components/responses/RouteNotFound"
  "/routes/{route_id}/remainder":
    get:
      summary: Return the remaining part of the route
      description: "Returns the specified route without the part behind the driver's position"
      operationId: app.routes.remainder
      parameters:
        - $ref: "#/components/parameters/routeID"
        - $ref: "#/components/parameters/LatLon"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feature"
                geometryType: LineString
        404:
          $ref: "#/components/responses/RouteNotFound"
  "/routes/{route_id}/candidates":
    post:
      summary: Find suitable passengers or drivers
      description: |
        This endpoint first filters, then sorts the canidate routes based on their proximity to route `route_id`.
        Sorting is ascending, i.e. the best candidate comes first.
      operationId: app.routes.get_candidates
      parameters:
        - $ref: "#/components/parameters/routeID"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                candidate_route_ids:
                  type: array
                  items:
                    type: string
                    format: uuid
              required:
                - candidate_route_ids
              additionalProperties: false
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feature"
                geometryType: LineString
        404:
          $ref: "#/components/responses/RouteNotFound"
  "/routes/{route_id}/suggest_pickup":
    get:
      summary: Suggest a pick-up point
      description: |
        Returns the nearest position on the driver's route which is reachable by foot from `position`
      operationId: app.routes.suggest_pickup
      parameters:
        - $ref: "#/components/parameters/routeID"
        - $ref: "#/components/parameters/LatLon"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  distance:
                    type: number
                    format: float
                  radius:
                    type: number
                    format: float
                  point:
                    $ref: "#/components/schemas/Position"
        404:
          $ref: "#/components/responses/RouteNotFound"
  "/pickup/{point_id}":
    get:
      summary: Get pick-up point
      description: Retrieve a pick-up point from the database
      operationId: app.routes.get_pickup_point
      parameters:
        - name: point_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Position"
        404:
          $ref: "#/components/responses/PickupPointNotFound"
  "/pickup":
    post:
      summary: Save a pick-up point
      description: Save a passenger pick-up point with a reference to their route
      operationId: app.routes.post_pickup_point
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                position:
                  $ref: "#/components/schemas/Position"
                route_id:
                  $ref: "#/components/schemas/UUID"
              required:
                - position
                - route_id
              additionalProperties: false
            examples:
              Save a point:
                summary: Save a pick-up point in the database
                externalValue: "https://drive-and-go.postman.co/workspace/20b6cba3-160c-4b6b-8daa-fcbc83b74000/example/5899615-d7af0b13-0333-4e46-945e-82ac75ae7b98"
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UUID"
          links:
            Get the point:
              operationId: app.routes.get_pickup_point
              parameters:
                point_id: $response.body
        400:
          description: Bad request, e.g. duplicate points or invalid parameters
        500:
          description: Server error. Often, an ORS error that may actually be cause by a bad request

  "/suggest":
    get:
      summary: Find addresses or POIs that match the text
      description: TODO
      operationId: app.routes.suggest
      parameters:
        - $ref: "#/components/parameters/Text"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Feature"
                  geometryType: Point
        400:
          description: "Please, specify what to search for"
        404:
          description: "Nothing found; try a different text"
  "/geocode":
    get:
      summary: Get coordinates of an address identified by text
      description: TODO
      operationId: app.routes.geocode
      parameters:
        - $ref: "#/components/parameters/Text"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Position"
        400:
          description: "`text` must be at least two characters long"
        404:
          description: Nothing found; try a different text
  "/reverse":
    get:
      summary: Get an address or POI at position
      description: TODO
      operationId: app.routes.reverse_geocode
      parameters:
        - $ref: "#/components/parameters/LatLon"
      responses:
        200:
          description: The found address or POI as text
          content:
            application/json:
              schema:
                type: string
        400:
          description: "`position` must a valid lat,lon string"
        404:
          description: Nothing found at the given location
components:
  schemas:
    UUID:
      type: string
      format: uuid
      pattern: '^[a-fA-F0-9]{8}-?[a-fA-F0-9]{4}-?4[a-fA-F0-9]{3}-?[89ab][a-fA-F0-9]{3}-?[a-fA-F0-9]{12}\Z'
    Position:
      description: A [lat, lon] array (in this order because it comes from the GPS).
      externalDocs:
        url: "https://tools.ietf.org/html/rfc7946#section-3.1.1"
      type: array
      minItems: 2
      maxItems: 2
      items:
        type: number
        minimum: -90
        maximum: 180
      example: [55.5, 37.5432]
    LineString:
      description: A GeoJSON LineString object
      externalDocs:
        url: "https://tools.ietf.org/html/rfc7946#section-3.1.4"
      type: object
      properties:
        "type":
          type: string
          enum:
            - LineString
        coordinates:
          type: array
          minItems: 2
          items:
            $ref: "#/components/schemas/Position"
    Point:
      description: A GeoJSON Point object
      externalDocs:
        url: "https://tools.ietf.org/html/rfc7946#section-3.1.2"
      type: object
      properties:
        type:
          type: string
          enum:
            - Point
        coordinates:
          $ref: "#/components/schemas/Position"
    Feature:
      description: A GeoJSON Feature object
      externalDocs:
        url: "https://tools.ietf.org/html/rfc7946#section-3.2"
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UUID"
        geometry:
          oneOf:
            - $ref: "#/components/schemas/Point"
            - $ref: "#/components/schemas/LineString"
          discriminator:
            propertyName: geometryType
        properties:
          type: object
          nullable: true
      required:
        - geometry
        - properties
  parameters:
    routeID:
      name: route_id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/UUID"
    Text:
      name: text
      in: query
      required: true
      schema:
        type: string
        minLength: 2
    LatLon:
      name: position
      in: query
      description: A lat,lon string (may contain a space after the comma)
      required: true
      schema:
        type: string
        format: latlon
        pattern: '^\s*-?\d{1,2}(\.\d+)?,\s?-?\d{1,3}(\.\d+)?\s*\Z'
      example: "55.532,37.3433"
  responses:
    RouteNotFound:
      description: "No such route in the database :-("
    PickupPointNotFound:
      description: "No such pick-up point in the database :-("
  # securitySchemes:
  #   BasicAuth:
  #     type: http
  #     scheme: basic
# security:
#   - BasicAuth: []
