"""PickupPoint: route id instead of trip id and user id

Revision ID: 00ce4fb4831a
Revises: 63427ca15da6
Create Date: 2021-08-16 13:23:22.545096

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00ce4fb4831a'
down_revision = '63427ca15da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pickup_point', 'route', ['route_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_point', sa.Column('trip_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('pickup_point', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pickup_point', type_='foreignkey')
    op.drop_column('pickup_point', 'created_at')
    op.drop_column('pickup_point', 'route_id')
    # ### end Alembic commands ###
