"""Make trip_id unique

Revision ID: 08ef7a2da591
Revises: cb89236ef3e2
Create Date: 2021-06-08 14:15:21.305893

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ef7a2da591'
down_revision = 'cb89236ef3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_route_finish', table_name='route')
    op.drop_index('idx_route_route', table_name='route')
    op.drop_index('idx_route_start', table_name='route')
    op.create_unique_constraint(None, 'route', ['trip_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route', type_='unique')
    op.create_index('idx_route_start', 'route', ['start'], unique=False)
    op.create_index('idx_route_route', 'route', ['route'], unique=False)
    op.create_index('idx_route_finish', 'route', ['finish'], unique=False)
    # ### end Alembic commands ###
