"""Add drop-off point backref to Route

Revision ID: 12e1cb995194
Revises: d647c9e431a2
Create Date: 2021-08-26 15:41:09.428082

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12e1cb995194'
down_revision = 'd647c9e431a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dropoff_point',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('route_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dropoff_point')
    # ### end Alembic commands ###
