"""Remove start & finish from route; rename geom to geog

Revision ID: 45bc2c33460c
Revises: a15a870edf3d
Create Date: 2021-08-22 15:47:30.211045

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '45bc2c33460c'
down_revision = 'a15a870edf3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('geog', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.drop_column('route', 'route')
    op.drop_column('route', 'start')
    op.drop_column('route', 'finish')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('finish', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), autoincrement=False, nullable=False))
    op.add_column('route', sa.Column('start', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), autoincrement=False, nullable=False))
    op.add_column('route', sa.Column('route', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, from_text='ST_GeogFromText', name='geography'), autoincrement=False, nullable=True))
    op.drop_column('route', 'geog')
    # ### end Alembic commands ###
