"""empty message

Revision ID: 63427ca15da6
Revises: 481750009405
Create Date: 2021-08-08 21:33:18.293870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63427ca15da6'
down_revision = '481750009405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pickup_point', 'trip_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_index('idx_pickup_point_geom', table_name='pickup_point')
    op.drop_constraint('pickup_point_trip_id_key', 'pickup_point', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pickup_point_trip_id_key', 'pickup_point', ['trip_id'])
    op.create_index('idx_pickup_point_geom', 'pickup_point', ['geom'], unique=False)
    op.alter_column('pickup_point', 'trip_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
