"""Add Start, Finish & Route

Revision ID: 6ddc736449fe
Revises: 
Create Date: 2021-06-06 14:05:32.022988

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2  
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ddc736449fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finish',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeomFromGeoJSON', name='geography'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromGeoJSON', name='geography'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('start',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeomFromGeoJSON', name='geography'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('start')
    op.drop_table('route')
    op.drop_table('finish')
    # ### end Alembic commands ###
