"""Delete pick-up point when its route is deleted

Revision ID: 8ab5a0d208c5
Revises: 044446c8c4e5
Create Date: 2021-08-16 17:44:14.086517

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '8ab5a0d208c5'
down_revision = '044446c8c4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pickup_point_route_id_fkey', 'pickup_point', type_='foreignkey')
    op.create_foreign_key(None, 'pickup_point', 'route', ['route_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pickup_point', type_='foreignkey')
    op.create_foreign_key('pickup_point_route_id_fkey', 'pickup_point', 'route', ['route_id'], ['id'])
    # ### end Alembic commands ###
