"""Do not use list in route pickup point id backref

Revision ID: a15a870edf3d
Revises: a96cb642cac7
Create Date: 2021-08-22 12:19:25.662089

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a15a870edf3d'
down_revision = 'a96cb642cac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pickup_point_route_id_fkey1', 'pickup_point', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('pickup_point_route_id_fkey1', 'pickup_point', 'route', ['route_id'], ['id'])
    # ### end Alembic commands ###
