"""empty message

Revision ID: c20b12b4e3da
Revises: d05f4bcf7d69
Create Date: 2021-08-15 09:21:16.122576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c20b12b4e3da'
down_revision = 'd05f4bcf7d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_point', sa.Column('route_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'pickup_point', 'route', ['route_id'], ['id'])
    op.drop_column('pickup_point', 'trip_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_point', sa.Column('trip_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pickup_point', type_='foreignkey')
    op.drop_column('pickup_point', 'route_id')
    # ### end Alembic commands ###
