"""Add created_at to PickupPoint

Revision ID: d05f4bcf7d69
Revises: 63427ca15da6
Create Date: 2021-08-12 10:29:24.166640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd05f4bcf7d69'
down_revision = '63427ca15da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_point', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('pickup_point', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_point', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('pickup_point', 'created_at')
    # ### end Alembic commands ###
