"""Add spatial indexes

Revision ID: d58a6d99cebc
Revises: b78044fe6891
Create Date: 2021-09-27 21:46:36.352453

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd58a6d99cebc'
down_revision = 'b78044fe6891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_dropoff_point_geom', 'dropoff_point', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_pickup_point_geom', 'pickup_point', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_route_geom', 'route', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_route_geom', table_name='route', postgresql_using='gist')
    op.drop_index('idx_pickup_point_geom', table_name='pickup_point', postgresql_using='gist')
    op.drop_index('idx_dropoff_point_geom', table_name='dropoff_point', postgresql_using='gist')
    # ### end Alembic commands ###
