"""Rename geom to geo in pickup_point for consistency

Revision ID: d647c9e431a2
Revises: 45bc2c33460c
Create Date: 2021-08-22 16:19:10.967789

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd647c9e431a2'
down_revision = '45bc2c33460c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_point', sa.Column('geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=False))
    op.drop_column('pickup_point', 'geom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_point', sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), autoincrement=False, nullable=False))
    op.drop_column('pickup_point', 'geog')
    # ### end Alembic commands ###
